namespace Nelt.Application.Abstractions;

/// <summary>
/// Binary storage for uploads (videos, audio, documents, images). Keys are opaque, generated by the storage.
/// The default implementation writes to disk; swap for blob storage when scaling out.
/// </summary>
public interface IFileStorage
{
    Task<string> SaveAsync(Stream content, string folder, string extension, CancellationToken cancellationToken = default);

    /// <summary>Opens a seekable read stream, or null when the object does not exist.</summary>
    Task<Stream?> OpenReadAsync(string key, CancellationToken cancellationToken = default);

    Task DeleteAsync(string key, CancellationToken cancellationToken = default);
}
