#!/usr/bin/env python3
"""Generates Resources/SharedResource.{de,ar,zh}.resx from Resources/i18n/*.txt.

Each line of the source files is:  English key|Deutsch|العربية|中文
English text is the lookup key, so English needs no resource file (missing entries fall back to it).
Run after editing translations:  python3 tools/build_resx.py
"""
import glob, os
from xml.sax.saxutils import escape

here = os.path.dirname(os.path.abspath(__file__))
res = os.path.join(here, "..", "src", "Nelt.Web", "Resources")
rows = {}
for path in sorted(glob.glob(os.path.join(res, "i18n", "*.txt"))):
    for n, line in enumerate(open(path, encoding="utf-8"), 1):
        line = line.rstrip("\n")
        if not line.strip() or line.startswith("#"):
            continue
        parts = line.split("|")
        if len(parts) != 4:
            raise SystemExit(f"{os.path.basename(path)}:{n}: expected 4 columns, got {len(parts)}")
        rows[parts[0]] = parts[1:]

header = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/build_resx.py from Resources/i18n/*.txt. Do not edit by hand. -->
<root>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
"""
for i, culture in enumerate(("de", "ar", "zh")):
    with open(os.path.join(res, f"SharedResource.{culture}.resx"), "w", encoding="utf-8") as f:
        f.write(header)
        for key in sorted(rows):
            f.write(f'  <data name="{escape(key, {chr(34): "&quot;"})}" xml:space="preserve"><value>{escape(rows[key][i])}</value></data>\n')
        f.write("</root>\n")
print(f"{len(rows)} strings written for de, ar, zh")
